# Библиотека Numpy

### Подключение библиотеки

In [16]:
import numpy as np

### Создание массива размерностью 2x3

In [4]:
a = np.array([
    [1, 2, 3],
    [2,3,1]
    ])
a

array([[1, 2, 3],
       [2, 3, 1]])

### Вывести форму (shape), длинну массива (в данном случае число массивов внутри массива) (len) и количество элементов в массиве

In [6]:
print( a.shape )
print( len(a) )
print( a.size )

(2, 3)
2
6


### Создание массива нулей и единиц заданной размерности

In [7]:
b = np.zeros((3, 5))
print(b)

print()

c = np.ones((3, 5))
print(c)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### Создание массива элементов в пределе a,b с шагом c

In [ ]:
c = np.arange(0, 1, 0.1)
c

###  Создание массива из c  элементов равномерно распределенных чисел в пределах a,b 

In [9]:
c = np.linspace(1, 2, 5)
c

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

### Создание массива при помощи функции

In [12]:
def f1(i, j):
     return 3 * i + j

a = np.fromfunction(f1, (3, 4))
a

array([[0., 1., 2., 3.],
       [3., 4., 5., 6.],
       [6., 7., 8., 9.]])

### Тип элементов массива

In [18]:
a.dtype, a.dtype.name

(dtype('float64'), 'float64')

### Перевод элементов массива в другой тип

In [20]:
print( a.astype(int) )
print( a.astype(str) )

[[0 1 2 3]
 [3 4 5 6]
 [6 7 8 9]]
[['0.0' '1.0' '2.0' '3.0']
 ['3.0' '4.0' '5.0' '6.0']
 ['6.0' '7.0' '8.0' '9.0']]


### Итерация по элементам массива:

In [22]:
for i in a:
    print(i)

[0. 1. 2. 3.]
[3. 4. 5. 6.]
[6. 7. 8. 9.]


### Математические операции между массивами

In [27]:
a = np.array([1 , 2 , 3])


b = np.array([4 , 5 , 6])

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** 2)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


### Синус от всех элементов массива

In [28]:
print(np.sin(a))

[0.84147098 0.90929743 0.14112001]


### Сравнение массивов поэлементно

In [29]:
print(a == b)

[False False False]


### Сумма элементов массива, максимальный элемент массива, минимальный элемент массива, среднее значение элементов массива

In [30]:
b.sum(), b.max(), b.min(), b.mean()

(15, 6, 4, 5.0)

### Сортировка массива

In [33]:
print( b[::-1] )
print( np.sort(b[::-1]) )

[6 5 4]
[4 5 6]


### Удаление элемента массива с указанным индексом

In [35]:
print(a)
a = np.delete(a, [2])
print(a)

[1 2 3]
[1 2]


### Добавление указанного элемента в массив на указанную позицию

In [40]:
a = np.insert(a, 2, [3])
print(a)

[1 2 3]


### Обращение к элементам массива в указанных пределах

In [44]:
b = a[1:2]
print(b)

[2]


### При переприсвоении значения нового массива перепроисвоится значение и родительского массива

In [45]:
b[0] = 99
print(a)
print(b)

[ 1 99  3]
[99]


### Если необходимо создать массив из выбранных элементов и изменять его независимо от родительского массива, используется копирование

In [48]:
a = [1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 9]
b = a.copy()
b[0]=99
print(a)
print(b)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[99, 2, 3, 4, 5, 6, 7, 8, 9]


### Обращение к элементам массива с шагом

In [49]:
b = a[1:10:2]
print(b)

[2, 4, 6, 8]


### Изменение текущей формы массива на заданную

In [65]:
a = np.array([
            [ 1 , 2 ],
            [ 3 , 4]
             ])
print(a)
print(a.shape)

print()

a = a.reshape(1,4)
print(a)
print(a.shape)

[[1 2]
 [3 4]]
(2, 2)

[[1 2 3 4]]
(1, 4)


### Уменьшение размерности формы массива

In [66]:
a = a.reshape(2,2)
a = a.reshape(-1)
print(a)
print(a.shape)

[1 2 3 4]
(4,)


### Объединение массивов горизонтально

In [68]:
a = np.array([ 1 , 2 , 3])
b = np.array([ 4 , 5 , 6])

print(np.hstack((a, b)))

[1 2 3 4 5 6]


### Объединение массивов вертикально 

In [72]:
np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

### Сохранение массива данных в текстовый файл с указанным разделителем

In [77]:
np.savetxt('example.txt', a, delimiter=';')

### Загрузка массива данных из указанного файла с указанным разделителем

In [76]:
a = np.loadtxt('example.txt', delimiter=';')
print(a)

[1. 2. 3.]


# Решение СЛАУ

In [78]:
left = np.array( [ [1, 3], [2, -4] ] )
right = np.array( [9, 8] )
np.linalg.solve(left, right)

array([6., 1.])

### Разделение указанного предложения на слова по заданному разделителю

In [82]:
a = np.array('Раз два три четыре'.split(' '))
b = np.array('One two three four'.split(' '))
print(a)
print(b)

['Раз' 'два' 'три' 'четыре']
['One' 'two' 'three' 'four']


### Замена первых букв на заглавные, всех букв на заглавные и всех букв на прописные

In [84]:
print(np.char.capitalize(a))
print(np.char.upper(a))
print(np.char.lower(a))

['Раз' 'Два' 'Три' 'Четыре']
['РАЗ' 'ДВА' 'ТРИ' 'ЧЕТЫРЕ']
['раз' 'два' 'три' 'четыре']


### Конкатенация двух массивов строк и массива строки с заданным символом

In [86]:
print(np.char.add(a, b))
print(np.char.add(a, '_'))

['РазOne' 'дваtwo' 'триthree' 'четыреfour']
['Раз_' 'два_' 'три_' 'четыре_']


### Проверка на соответствие начала и конца каждой строки в массиве с указанными символами

In [87]:
st = np.array(['One', 'two', 'three', 'four', '12', '-14'])

print(np.char.startswith(st, 't'))
print(np.char.endswith(st, 'e'))

[False  True  True False False False]
[ True False  True False False False]


### Количество указанных букв в каждой строке массива и проверка на то, является ли строка числом

In [89]:
print(np.char.count(st, 'e'))

print(np.char.isdigit(st))

[1 0 2 0 0 0]
[False False False False  True False]


# Домашнее задание